apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edisonapi
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx-api"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - edisonapi.eastus.cloudapp.azure.com
    secretName: tls-secret-api
  rules:
  - host: edisonapi.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: edisonapi
          servicePort: 80
      - path: /chat
        backend:
          serviceName: edisonchatservice
          servicePort: 80
      - path: /deviceprovisioning
        backend:
          serviceName: edisondeviceprovisioning
          servicePort: 80