apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: abi-rabbit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: abi-rabbit
    spec:
      containers:
      - name: abi-rabbit
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: abi-rabbit
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: Username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: Password
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisonadminportal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisonadminportal
    spec:
      containers:
      - name: edisonadminportal
        image: edisondevcontainerregistry.azurecr.io/edisonadminportal:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
        ports:
        - containerPort: 80
          name: adminportal
      volumes:
      - name: config
        configMap:
          name: config-edisonadminportal
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication
---      
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisonapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisonapi
    spec:
      containers:
      - name: edisonapi
        image: edisondevcontainerregistry.azurecr.io/edisonapi:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
        ports:
        - containerPort: 80
          name: api
      volumes:
      - name: config
        configMap:
          name: config-edisonapi
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication
---      
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisonworkflows
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisonworkflows
    spec:
      containers:
      - name: edisonworkflows
        image: edisondevcontainerregistry.azurecr.io/edisonworkflows:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: config-edisonworkflows
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication
---      
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisonmessagedispatcherservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisonmessagedispatcherservice
    spec:
      containers:
      - name: edisonmessagedispatcherservice
        image: edisondevcontainerregistry.azurecr.io/edisonmessagedispatcherservice:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: config-edisonmessagedispatcherservice
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication
---     
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisoneventprocessorservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisoneventprocessorservice
    spec:
      containers:
      - name: edisoneventprocessorservice
        image: edisondevcontainerregistry.azurecr.io/edisoneventprocessorservice:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: config-edisoneventprocessorservice
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication
---      
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisondevicesynchronizationservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisondevicesynchronizationservice
    spec:
      containers:
      - name: edisondevicesynchronizationservice
        image: edisondevcontainerregistry.azurecr.io/edisondevicesynchronizationservice:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: config-edisondevicesynchronizationservice
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication
---      
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisoniothubcontrollerservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisoniothubcontrollerservice
    spec:
      containers:
      - name: edisoniothubcontrollerservice
        image: edisondevcontainerregistry.azurecr.io/edisoniothubcontrollerservice:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: config-edisoniothubcontrollerservice
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication
---      
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisonsignalrservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisonsignalrservice
    spec:
      containers:
      - name: edisonsignalrservice
        image: edisondevcontainerregistry.azurecr.io/edisonsignalrservice:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: config-edisonsignalrservice
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication
---      
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisonchatservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisonchatservice
    spec:
      containers:
      - name: edisonchatservice
        image: edisondevcontainerregistry.azurecr.io/edisonchatservice:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: config-edisonchatservice
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication
---    
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisonresponseservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisonresponseservice
    spec:
      containers:
      - name: edisonresponseservice
        image: edisondevcontainerregistry.azurecr.io/edisonresponseservice:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: config-edisonresponseservice
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edisondeviceprovisioning
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edisondeviceprovisioning
    spec:
      containers:
      - name: edisondeviceprovisioning
        image: edisondevcontainerregistry.azurecr.io/edisondeviceprovisioning:latest
        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true 
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
        ports:
        - containerPort: 80
          name: deviceprov
      volumes:
      - name: config
        configMap:
          name: config-edisondeviceprovisioning
      - name: secrets
        secret:
          secretName: secrets-common
      imagePullSecrets:
      - name: acr-authentication